### ISSUE TITLE
会员中心插件

### ISSUE THREAD

**Issue by masterZSH** [karsonzhang/fastadmin-addons#2]
修改会员中心插件 User.php 新增这两个方法 同那个pr 
` /**
     * 插件禁用方法
     */
    public function disable()
    {
        \app\common\library\Menu::delete('user');
        return true;
    }

    /**
     * 插件启用方法
     */
    public function enable()
    {
        \app\common\library\Menu::create([
            [
                'name'    => 'user',
                'title'   => '会员管理',
                'icon'    => 'fa fa-user-o',
                'remark'  => '用于管理前台注册的会员',
                'sublist' => [
                    ['name' => 'user/index', 'title' => '查看'],
                    ['name' => 'user/edit', 'title' => '修改'],
                    ['name' => 'user/del', 'title' => '删除'],
                    ['name' => 'user/multi', 'title' => '批量更新'],
                ]
            ]
        ]);
        return true;
    }`

**Comment by karsonzhang** [comment]
@masterZSH 目前最新版FA的Menu类已经直接了enable和disable方法
